In [1]:
import numpy as np

np.random.seed(0)
np.set_printoptions(precision=5, suppress=True)

# Generate 3 random 3x3 matrices
matrices = [np.random.randint(-10, 11, (3, 3)) for _ in range(3)]

# Compute their inverses and products with their inverses
inverses = [np.linalg.inv(m) for m in matrices]
products = [m @ inv for m, inv in zip(matrices, inverses)]

# Print matrices, inverses, and products
for i, (m, inv, prod) in enumerate(zip(matrices, inverses, products), 1):
    print(f"Matrix {i}:\n{m}\n\nInverse of Matrix {i}:\n{inv}\n\nProduct of Matrix {i} and its inverse:\n{prod}\n")


Matrix 1:
[[  2   5 -10]
 [ -7  -7  -3]
 [ -1   9   8]]

Inverse of Matrix 1:
[[-0.03095 -0.13874 -0.09072]
 [ 0.06297  0.0064   0.08111]
 [-0.07471 -0.02455  0.02241]]

Product of Matrix 1 and its inverse:
[[ 1.  0.  0.]
 [-0.  1. -0.]
 [ 0.  0.  1.]]

Matrix 2:
[[-6 -4  2]
 [-9 -4 -3]
 [ 4  7 -5]]

Inverse of Matrix 2:
[[-0.36607  0.05357 -0.17857]
 [ 0.50893 -0.19643  0.32143]
 [ 0.41964 -0.23214  0.10714]]

Product of Matrix 2 and its inverse:
[[ 1.  0. -0.]
 [-0.  1. -0.]
 [-0.  0.  1.]]

Matrix 3:
[[ 3 -2 -1]
 [10  9  6]
 [ 9 -5  5]]

Inverse of Matrix 3:
[[ 0.21552  0.0431  -0.00862]
 [ 0.01149  0.06897 -0.08046]
 [-0.37644 -0.00862  0.13506]]

Product of Matrix 3 and its inverse:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [ ]:
import numpy as np
import random as rd

# Function to generate a 3x3 random matrix of size with entries from -10 to 10
def gen_rd_matrix():
    return np.random.randint(-10, 11, size=(3, 3))

# The 3 generated matrices
matrix1 = gen_rd_matrix()
matrix2 = gen_rd_matrix()
matrix3 = gen_rd_matrix()

# The inverses of the 3 generated matrices
inverse_matrix1 = np.linalg.inv(matrix1)
inverse_matrix2 = np.linalg.inv(matrix2)
inverse_matrix3 = np.linalg.inv(matrix3)

# The product of the matrices with their inverse
product1 = matrix1 @ inverse_matrix1
product2 = matrix2 @ inverse_matrix2
product3 = matrix3 @ inverse_matrix3

# Print the matrices
print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix 3:")
print(matrix3)

# Print the inverses
print("\nInverse of Matrix 1:")
print(inverse_matrix1)

print("\nInverse of Matrix 2:")
print(inverse_matrix2)

print("\nInverse of Matrix 3:")
print(inverse_matrix3)


# Print the products
print("\nProduct of Matrix 1 and its inverse:")
print(product1)

print("\nProduct of Matrix 2 and its inverse:")
print(product2)

print("\nProduct of Matrix 3 and its inverse:")
print(product3)

Matrix 1:
[[ 8  2 -9]
 [-4  1 -7]
 [ 4 10 -7]]

Matrix 2:
[[ 2  1  3]
 [ 1 -9 -8]
 [ 0  8 -1]]

Matrix 3:
[[-6  7  4]
 [ 5 -4 -8]
 [ 7 -6 -5]]

Inverse of Matrix 1:
[[ 0.07994924 -0.0964467  -0.00634518]
 [-0.07106599 -0.02538071  0.11675127]
 [-0.05583756 -0.09137056  0.02030457]]

Inverse of Matrix 2:
[[ 0.42690058  0.14619883  0.11111111]
 [ 0.00584795 -0.01169591  0.11111111]
 [ 0.04678363 -0.09356725 -0.11111111]]

Inverse of Matrix 3:
[[ 0.49122807 -0.19298246  0.70175439]
 [ 0.54385965 -0.03508772  0.49122807]
 [ 0.03508772 -0.22807018  0.19298246]]

Product of Matrix 1 and its inverse:
[[ 1.00000000e+00 -5.55111512e-17  6.93889390e-18]
 [ 5.55111512e-17  1.00000000e+00 -6.93889390e-18]
 [-5.55111512e-17  5.55111512e-17  1.00000000e+00]]

Product of Matrix 2 and its inverse:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 2.08166817e-17 -4.16333634e-17  1.00000000e+00]]

Product of Matrix 3 and its inverse:
[[ 1.00000000e+