In [1]:
import numpy as np
import random as rd

# Function to generate a 3x3 random matrix of size with entries from -10 to 10
def gen_rd_matrix():
    return np.random.randint(-10, 11, size=(3, 3))

# The 3 generated matrices
matrix1 = gen_rd_matrix()
matrix2 = gen_rd_matrix()
matrix3 = gen_rd_matrix()

# The inverses of the 3 generated matrices
inverse_matrix1 = np.linalg.inv(matrix1)
inverse_matrix2 = np.linalg.inv(matrix2)
inverse_matrix3 = np.linalg.inv(matrix3)

# The product of the matrices with their inverse
product1 = matrix1 @ inverse_matrix1
product2 = matrix2 @ inverse_matrix2
product3 = matrix3 @ inverse_matrix3

# Print the matrices
print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix 3:")
print(matrix3)

# Print the inverses
print("\nInverse of Matrix 1:")
print(inverse_matrix1)

print("\nInverse of Matrix 2:")
print(inverse_matrix2)

print("\nInverse of Matrix 3:")
print(inverse_matrix3)


# Print the products
print("\nProduct of Matrix 1 and its inverse:")
print(product1)

print("\nProduct of Matrix 2 and its inverse:")
print(product2)

print("\nProduct of Matrix 3 and its inverse:")
print(product3)

Matrix 1:
[[ 8  2 -9]
 [-4  1 -7]
 [ 4 10 -7]]

Matrix 2:
[[ 2  1  3]
 [ 1 -9 -8]
 [ 0  8 -1]]

Matrix 3:
[[-6  7  4]
 [ 5 -4 -8]
 [ 7 -6 -5]]

Inverse of Matrix 1:
[[ 0.07994924 -0.0964467  -0.00634518]
 [-0.07106599 -0.02538071  0.11675127]
 [-0.05583756 -0.09137056  0.02030457]]

Inverse of Matrix 2:
[[ 0.42690058  0.14619883  0.11111111]
 [ 0.00584795 -0.01169591  0.11111111]
 [ 0.04678363 -0.09356725 -0.11111111]]

Inverse of Matrix 3:
[[ 0.49122807 -0.19298246  0.70175439]
 [ 0.54385965 -0.03508772  0.49122807]
 [ 0.03508772 -0.22807018  0.19298246]]

Product of Matrix 1 and its inverse:
[[ 1.00000000e+00 -5.55111512e-17  6.93889390e-18]
 [ 5.55111512e-17  1.00000000e+00 -6.93889390e-18]
 [-5.55111512e-17  5.55111512e-17  1.00000000e+00]]

Product of Matrix 2 and its inverse:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 2.08166817e-17 -4.16333634e-17  1.00000000e+00]]

Product of Matrix 3 and its inverse:
[[ 1.00000000e+